[dev]
dev1 ansible_host=
dev2 ansible_host=

[stg]
stg1 ansible_host=
stg2 ansible_host=
stg3 ansible_host=

[prod]
prod1 ansible_host=
prod2 ansible_host=
prod3 ansible_host=
prod4 ansible_host=

[all:var]
ansible_python_interpreter=usr/bin/python3
ansible_user=ubuntu
ansible_ssh_private_key_file=/Users/rdn/Documents/Project/Terraform/id_ed25519
