- name: Show Secrets
  hosts: dev
  become: true
  vars_files:
    - secrets.yml

  tasks:
    - name: Show Password 
      debug:
        msg: "My Password {{ password }}"
      no_log: true
    - name: Show API Key 
      debug:
        msg: "My API Key {{ api_key }}"
      no_log: true