---
- name: Include OS-specific tasks
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
  become: true

- name: Deploy MOTD
  template:
    src: motd.j2
    dest: /etc/motd
    mode: '0644'
  become: true
